// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZNYIzta2B00-EoWjwk45zUTaVDwNQbRI',
    appId: '1:1048662375433:web:d3c7274814ccc2594accd8',
    messagingSenderId: '1048662375433',
    projectId: 'sign-in-da443',
    authDomain: 'sign-in-da443.firebaseapp.com',
    storageBucket: 'sign-in-da443.appspot.com',
    measurementId: 'G-NN58TJ3RVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwnq6NCGVsAvnSmXkeLtGIWK2kVYEKOnk',
    appId: '1:1048662375433:android:7dc0aa11d73848904accd8',
    messagingSenderId: '1048662375433',
    projectId: 'sign-in-da443',
    storageBucket: 'sign-in-da443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbvTncjiNBXGG1kKJylns_Rsv6ABnfL8U',
    appId: '1:1048662375433:ios:96320a4493887f244accd8',
    messagingSenderId: '1048662375433',
    projectId: 'sign-in-da443',
    storageBucket: 'sign-in-da443.appspot.com',
    iosClientId: '1048662375433-82ovapgtlmtoaltm8os4lu9hled0h6uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbvTncjiNBXGG1kKJylns_Rsv6ABnfL8U',
    appId: '1:1048662375433:ios:fed9f305d71d7f484accd8',
    messagingSenderId: '1048662375433',
    projectId: 'sign-in-da443',
    storageBucket: 'sign-in-da443.appspot.com',
    iosClientId: '1048662375433-2semi83b9d4nmfqi7628lto59osd14pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial1.RunnerTests',
  );
}
